# Generated by Django 5.0.2 on 2024-03-04 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(height_field=400, upload_to='images/', width_field=500)),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Home', 'Home'), ('EV', 'Eletroauta'), ('Tesla', 'Tesla'), ('C-EV', 'Čínské EV'), ('EU-EV', 'Evropské EV'), ('Other-EV', 'Jiné EV'), ('Battery', 'Baterie'), ('Charging', 'Nabíjení'), ('Technology', 'Technologie'), ('Ren-Sour', 'Obnovitelné zdroje'), ('FVE', 'Fotovoltaika'), ('Wind-E', 'Větrná energie'), ('Others', 'Jiné')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.author')),
                ('tags', models.ManyToManyField(related_name='articles', to='articles.tag')),
            ],
        ),
    ]
