# Generated by Django 5.0.2 on 2024-03-10 20:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.AddField(
            model_name='author',
            name='remark',
            field=tinymce.models.HTMLField(default='Napiš něco o sobě'),
        ),
    ]
