# Generated by Django 5.0.2 on 2024-03-12 20:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_author_email_author_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='remark',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
