# Generated by Django 5.0.2 on 2024-03-19 20:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_author_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
