# Generated by Django 5.0.2 on 2024-03-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_content_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Home', 'Home'), ('EV', 'Elektroauta'), ('Tesla', 'Tesla'), ('C-EV', 'Čínské EV'), ('EU-EV', 'Evropské EV'), ('Other-EV', 'Jiné EV'), ('Battery', 'Baterie'), ('Charging', 'Nabíjení'), ('Technology', 'Technologie'), ('Ren-Sour', 'Obnovitelné zdroje'), ('FVE', 'Fotovoltaika'), ('Wind-E', 'Větrná energie'), ('Others', 'Jiné')], max_length=20),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
