# Generated by Django 5.0.2 on 2024-03-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_category_alter_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, height_field=400, upload_to='images/', width_field=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='remark',
            field=models.CharField(max_length=100),
        ),
    ]
